# Generated by Django 6.0.7 on 2026-07-10 07:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryFacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'ordering': ['facet_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryFacetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('topics', models.ManyToManyField(blank=True, related_name='directory_channels', to='core.topic')),
                ('facets', models.ManyToManyField(blank=True, related_name='channels', to='directories.directoryfacet')),
            ],
            options={
                'verbose_name': 'Directory channel',
            },
        ),
        migrations.AddField(
            model_name='directoryfacet',
            name='facet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facets', to='directories.directoryfacettype'),
        ),
        migrations.CreateModel(
            name='DirectoryOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('facets', models.ManyToManyField(blank=True, related_name='%(class)s_entries', to='directories.directoryfacet')),
                ('other_channels', models.ManyToManyField(blank=True, related_name='%(class)s_other_entries', to='directories.directorychannel')),
                ('primary_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='directories.directorychannel')),
                ('topics', models.ManyToManyField(blank=True, related_name='%(class)s_entries', to='core.topic')),
            ],
            options={
                'verbose_name': 'Directory organisation',
            },
        ),
        migrations.CreateModel(
            name='DirectoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('facets', models.ManyToManyField(blank=True, related_name='%(class)s_entries', to='directories.directoryfacet')),
                ('other_channels', models.ManyToManyField(blank=True, related_name='%(class)s_other_entries', to='directories.directorychannel')),
                ('primary_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='directories.directorychannel')),
                ('topics', models.ManyToManyField(blank=True, related_name='%(class)s_entries', to='core.topic')),
            ],
            options={
                'verbose_name': 'Directory page',
            },
        ),
        migrations.CreateModel(
            name='DirectoryVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_hours', models.TextField(blank=True)),
                ('facets', models.ManyToManyField(blank=True, related_name='%(class)s_entries', to='directories.directoryfacet')),
                ('other_channels', models.ManyToManyField(blank=True, related_name='%(class)s_other_entries', to='directories.directorychannel')),
                ('primary_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='directories.directorychannel')),
                ('topics', models.ManyToManyField(blank=True, related_name='%(class)s_entries', to='core.topic')),
            ],
            options={
                'verbose_name': 'Directory venue',
            },
        ),
        migrations.AlterUniqueTogether(
            name='directoryfacet',
            unique_together={('facet_type', 'slug')},
        ),
    ]
