# Generated by Django 6.0.7 on 2026-07-10 07:56

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('announce', 'Announcement'), ('minor', 'Minor'), ('major', 'Major'), ('notable-person', 'Notable person')], default='announce', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, default='More information', max_length=100)),
            ],
            options={
                'verbose_name': 'Alert banner',
                'ordering': ['-created'],
            },
        ),
    ]
