# Generated by Django 6.0.7 on 2026-07-10 07:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubsiteOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('domain', models.CharField(blank=True, help_text='Optional subsite domain', max_length=255)),
                ('featured_image', models.ImageField(blank=True, upload_to='subsites/')),
            ],
            options={
                'verbose_name': 'Subsite overview',
                'verbose_name_plural': 'Subsite overviews',
            },
        ),
        migrations.CreateModel(
            name='SubsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('subsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='subsites.subsiteoverview')),
            ],
            options={
                'verbose_name': 'Subsite page',
            },
        ),
    ]
